/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'angel' at '7/9/15 3:26 PM' with Gradle 2.4
 *
 * @author angel, @date 7/9/15 3:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
